# Generated by Django 3.2 on 2022-08-31 07:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('noticias_id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen_noticias', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('descripcion', models.TextField()),
                ('video', models.TextField()),
                ('informacion', models.TextField()),
            ],
            options={
                'db_table': 'tbl_noticias',
            },
        ),
    ]
