# Generated by Django 3.2 on 2022-09-01 19:17

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('testimonio_id', models.AutoField(primary_key=True, serialize=False)),
                ('foto', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'tbl_testimonio',
            },
        ),
    ]
